imports:
    - { resource: tables.yml }
services:
    alg.adminnotifications.listener:
        class: alg\adminnotifications\event\listener
        arguments:
        tags:
            - { name: event.listener }
    alg.adminnotifications.adminnotifications_handler:
        class: alg\adminnotifications\controller\adminnotifications_handler
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@request'
            - '@notification_manager'
            - '%tables.adminnotifications%'
    alg.adminnotifications.notification.type.fromadmin:
        class: alg\adminnotifications\notification\fromadmin
        shared: false
        parent: notification.type.base
        calls:
            - [set_user_loader, ['@user_loader']]
            - [set_notifications_table, ['%tables.notifications%']]
        tags:
            - { name: notification.type }
